services:
  - type: web
    name: google-alerts-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SMARTSUITE_API_KEY
        sync: false
      - key: SMARTSUITE_WORKSPACE
        value: sxs77u60
      - key: SMARTSUITE_TABLE_ID
        value: 68517b0036a5ddf3941ea848
