services:
  - type: web
    name: google-alerts-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
